spring.application.name=bookshop

server.port=8444

book.unit.price=50.0

management.endpoints.web.exposure.include=health,info,metrics,loggers
management.endpoint.health.show-details=when_authorized
management.info.env.enabled=true
info.app.name=BookShop Service Api
info.app.description=Pricing service for book baskets.
info.app.version=1.0.0

